import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}
java {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}
kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

repositories {
    maven { url = 'https://maven.brott.dev/' }
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    implementation project(":CommonLibs")

    implementation 'com.acmerobotics.roadrunner:MeepMeep:0.1.7'
    implementation 'com.github.ProNoob1029.PsiKit:core:0.2.0-beta1-ex4'
}